services:
  database:
    container_name: postgresql_database
    image: postgres:17.0
    restart: unless-stopped
    env_file:
      - project.env
  
  database-migrations:
    image: flyway/flyway:10
    env_file:
      - project.env
    depends_on:
      - database
    ports:
      - "9090:9090"
    volumes:
      - ./database-migrations:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

  server:
    build: server
    restart: unless-stopped
    volumes:
      - ./server:/app
    env_file:
      - project.env
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server-router.entrypoints=web"
      - "traefik.http.routers.server-router.rule=PathPrefix(`/api`)"
      - "traefik.http.services.server-service.loadbalancer.server.port=8000"

  redis:
    image: redis:7.4.2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  grader:
    build: grader
    restart: unless-stopped
    volumes:
      - ./grader:/app
    env_file:
      - project.env
    depends_on:
      - database
      - redis
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grader-api.rule=PathPrefix(`/grader-api`)"
      - "traefik.http.routers.grader-api.middlewares=grader-api-replacepath"
      - "traefik.http.middlewares.grader-api-replacepath.replacePathRegex.regex=^/grader-api(.*)"
      - "traefik.http.middlewares.grader-api-replacepath.replacePathRegex.replacement=/api$1"
      - "traefik.http.services.grader-api.loadbalancer.server.port=8001"
  
  client:
    build: client
    restart: unless-stopped
    volumes:
      - ./client:/app
    depends_on:
      - server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-router.entrypoints=web"
      - "traefik.http.routers.client-router.rule=PathPrefix(`/`)"
      - "traefik.http.services.client-service.loadbalancer.server.port=4321"

  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
