services:
  database:
    container_name: postgresql_database
    image: postgres:17.0
    restart: unless-stopped
    env_file:
      - project.env
  
  database-migrations:
    image: flyway/flyway:10
    env_file:
      - project.env
    depends_on:
      - database
    volumes:
      - ./database-migrations:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

  server:
    build: server
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    env_file:
      - project.env
    depends_on:
      - database

  redis:
    image: redis:7.4.2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  grader:
    build: grader
    restart: unless-stopped
    volumes:
      - ./grader:/app
    env_file:
      - project.env
    ports:
      - 8001:8001
    depends_on:
      - database
      - redis
  
  client:
    build: client
    restart: unless-stopped
    volumes:
      - ./client:/app
    depends_on:
      - server
    ports:
      - 4321:4321

  